version: "3"
services:
  prom:
    image: prom/prometheus:v2.3.2
    hostname: prom.startdt.net
    volumes:
      - /opt/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/rules.yml:/etc/prometheus/rules.yml
      - /opt/rules:/etc/prometheus/rules
      - /opt/prometheus:/prometheus
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:v0.15.0
    hostname: alert.startdt.net
    container_name: alertmanager
    volumes: 
      - /opt/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
  pushgateway: 
    image: prom/pushgateway:v0.5.2
    container_name: pushgateway
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana:5.2.1
    hostname: grafana.startdt.net
    container_name: grafana
    volumes:
      - /opt/grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=#######
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.qiye.aliyun.com:465
      - GF_SMTP_USER=alert-monitor@startdt.com
      - GF_SMTP_PASSWORD=#######
      - GF_SMTP_FROM_ADDRESS=alert-monitor@startdt.com
      - GF_SERVER_ROOT_URL=http://grafana.startdt.net
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

