# 全局配置项
global:
  resolve_timeout: 5m #处理超时时间，默认为5min
  smtp_smarthost: 'smtp.163.com:465'   # 139发件服务器 ，同理也可设置qq企业，163邮箱等
  smtp_from: 'bz_monitor@163.com'
  smtp_auth_username: 'bz_monitor@163.com'
  smtp_auth_password: ''

# 定义路由树信息
route:
  group_by: ['alertname']   #定义分组规则标签
  group_wait: 30s           #定义一定时间内等待接收新的告警
  group_interval: 1m        #定义相同Group之间发送告警通知的时间间隔
  repeat_interval: 1h       #发送通知后的静默等待时间
  receiver: dingding_webhook # 发送警报的接收者的名称，以下receivers name的名称

  routes:
  - receiver: dingding_webhook
    match:
      severity: red|yellow  #将rules.yml里labels对应

  - receiver: bz
    match:
      severity: red|yellow  #将rules.yml里labels对应 
# 定义警报接收者信息
receivers:
  - name: 'bz'
    email_configs:
    - to: 'xiayun@startdt.com'
      require_tls: false

  - name: 'dingding_webhook'
    webhook_configs:
    - send_resolved: true
      url: http://172.16.18.6:8060/dingtalk/webhook1/send

# 一个inhibition规则是在与另一组匹配器匹配的警报存在的条件下，使匹配一组匹配器的警报失效的规则。两个警报必须具有一组相同的标签。
inhibit_rules:
  - source_match:
      alertname: InstanceDown
      severity: red
    target_match:
      severity: yellow
    equal: ['alertname','instance']

