groups:
- name: hostStatsAlert
  rules:
  - alert: hostCpuUsageAlert
    expr: sum(avg without (cpu)(irate(node_cpu_seconds_total{mode!='idle'}[5m]))) by (instance) > 0.8
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{ $labels.instance }} CPU usgae high"
      description: "{{ $labels.instance }} CPU usage above 85% (current value: {{ $value }})"
  - alert: hostMemUsageAlert
    expr: 1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes > 0.85
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{ $labels.instance }} MEM usgae high"
      description: "{{ $labels.instance }} MEM usage above 85% (current value: {{ $value }})"
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels: 
      severity: red
      warn: high
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 1 minutes."
  - alert: CPULoad5High
    expr: node_load5 > 5
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{$labels.instance}} CPU load-5m High"
      description: "{{$labels.instance}} of job {{$labels.job}} CPU load-5m was greater than 5 for more than 1 minutes (current value: {{ $value }})."
  - alert: FilesystemFree
    expr: node_filesystem_free_bytes{fstype!~"nsfs|rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev|none|devpts|sysfs|debugfs|fuse.*"} / node_filesystem_size_bytes{fstype!~"nsfs|rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev|none|devpts|sysfs|debugfs|fuse.*"} < 0.2
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{$labels.instance}} filesystem bytes was less than 20%"
      description: "{{$labels.instance}} of job {{$labels.job}} filesystem bytes usage above 80%"

- name: ngrokConnStatsAlert
  rules:
  - alert: ngrokConnStatsAlert
    expr: ngrok_Connect_Status != 0
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{ $labels.instance }} ngrok port lost connection"
      description: "{{ $labels.instance }} ngrok port lost connection"

- name: Java_Pid_Stats_Alert
  rules:
  - alert: java进程报警
    expr: java != 1
    for: 1m
    labels:
      severity: yellow
    annotations:
      summary: "Instance {{ $labels.instance }} java  not start"
      description: "{{ $labels.instance }} java not start"
