version: '2.1'
services:
 pg_prometheus:
   image: timescale/pg_prometheus:master
   command: -c synchronous_commit=OFF
   container_name: pg_prometheus
   ports:
   - "5432:5432"
   volumes:
     - pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=xxx
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 1s
     timeout: 5s  
     retries: 10
 prometheus_postgresql_adapter:
   image: timescale/prometheus-postgresql-adapter:master
   container_name: prom_pg_adapter
   ports:
     - "9201:9201"
   depends_on:
     pg_prometheus:
       condition: service_healthy
   command: "-pg.host=pg_prometheus -log.level=warn -pg.user=postgres -pg.password=xxx"
volumes:
   pgdata:
     external: true
