version: '2'
services:
  influxdb:
    image: influxdb
    command: -config /etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - /root/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin@123!
      - INFLUXDB_USER=prom
      - INFLUXDB_USER_PASSWORD=prom@123!
volumes:
   influxdb-data:
     external: true

